networks:
  - name: 'access'
    physical_network: 'datacentre'
    allocation_pool_start: '172.30.0.113'
    allocation_pool_end: '172.30.0.125'
    cidr: 172.30.0.112/28
    enable_dhcp: true
    gateway_ip: '172.30.0.1'
    external: true
    shared: true
    router_name: router1
    port_type: normal
    network_type: flat
