resource_registry:
  # Specify the relative/absolute path to the config files you want to use for override the default.
  OS::TripleO::ComputeOvsDpdkSriov::Net::SoftwareConfig: nic-configs/computeovsdpdksriov.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml
  OS::TripleO::ComputeOvsDpdkSriovMellanox::Net::SoftwareConfig: nic-configs/computeovsdpdksriovmellanox.yaml

parameter_defaults:
  # Customize all these values to match the local environment
  InternalApiNetCidr: 10.10.146.0/24
  TenantNetCidr: 10.10.147.0/24
  StorageNetCidr: 10.10.148.0/24
  StorageMgmtNetCidr: 10.10.149.0/24
  ExternalNetCidr: 10.35.141.46/28
  # CIDR subnet mask length for provisioning network
  ControlPlaneSubnetCidr: '24'
  InternalApiAllocationPools: [{'start': '10.10.146.100', 'end': '10.10.146.200'}]
  TenantAllocationPools: [{'start': '10.10.147.100', 'end': '10.10.147.200'}]
  StorageAllocationPools: [{'start': '10.10.148.100', 'end': '10.10.148.200'}]
  StorageMgmtAllocationPools: [{'start': '10.10.149.100', 'end': '10.10.149.200'}]
  # Use an External allocation pool which will leave room for floating IPs
  ExternalAllocationPools: [{'start': '10.35.141.33', 'end': '10.35.141.38'}]
  # Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: 10.35.141.46
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.0.30.1
  # Generally the IP of the Undercloud
  EC2MetadataIp: 192.0.30.1
  InternalApiNetworkVlanID: 546
  TenantNetworkVlanID: 547
  StorageNetworkVlanID: 548
  StorageMgmtNetworkVlanID: 549
  ExternalNetworkVlanID: 398
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["10.46.0.31","10.46.0.32"]
  # May set to br-ex if using floating IPs only on native VLAN on bridge br-ex
  NeutronExternalNetworkBridge: "''"
  # The tunnel type for the tenant network (vxlan or gre). Set to '' to disable tunneling.
  NeutronTunnelTypes: 'vxlan'
  # The tenant network type for Neutron (vlan or vxlan).
  #NeutronNetworkType: 'geneve'
  NeutronNetworkType: 'vxlan'
  # The OVS logical->physical bridge mappings to use.
  NeutronBridgeMappings: 'dpdk-mgmt:br-link0,dpdkdata1:br-dpdk1,dpdkdata2:br-dpdk2'
  # The Neutron ML2 and OpenVSwitch vlan mapping range to support.
  NeutronNetworkVLANRanges: 'dpdk-mgmt:399:399,dpdk-mgmt:550:550,dpdkdata1:551:551,dpdkdata2:552:552,sriov-1:30:30,sriov-2:31:31,sriov-3:32:32'
  # Nova flavor to use.
  OvercloudControllerFlavor: controller
  OvercloudComputeOvsDpdkSriovFlavor: compute
  OvercloudComputeOvsDpdkSriovMellanoxFlavor: mellanox
  # Number of nodes to deploy.
  ControllerCount: 3
  ComputeOvsDpdkSriovCount: 1
  ComputeOvsDpdkSriovMellanoxCount: 1
  # NTP server configuration.
  NtpServer: clock.redhat.com
  # MTU global configuration
  NeutronGlobalPhysnetMtu: 9000
  # Configure the classname of the firewall driver to use for implementing security groups.
  NeutronOVSFirewallDriver: openvswitch
  SshServerOptions:
    UseDns: 'no'

  ControllerHostnameFormat: 'controller-%index%'
  ComputeOvsDpdkSriovHostnameFormat: 'compute-%index%'
  ComputeOvsDpdkSriovMellanoxHostnameFormat: 'computemellanox-%index%'

  # Collectd server that will gather information from overcloud deployment - Service Assurance
  CollectdServer: 192.0.30.1
  CollectdConnectionType: "network"

  # Same parameter across the roles
  #OvsEnableDpdk: true
  #TunedProfileName: "cpu-partitioning"
  #IsolCpusList: "2-19,22-39"
  #NovaVcpuPinSet: ['4-19,24-39']
  #NovaReservedHostMemory: 4096
  #OvsDpdkSocketMemory: "3072,1024"
  #OvsDpdkMemoryChannels: "4"
  #OvsDpdkCoreList: "0,20,1,21"
  #OvsPmdCoreList: "2,22,3,23"
  #NovaComputeCpuSharedSet: [0,20,1,21]
    # below lines are for history - now this is resolved and we are not
    # required to pass extra hiera data variables - refer BZ -
    # https://bugzilla.redhat.com/show_bug.cgi?id=1617927
  #NovaLibvirtRxQueueSize: 1024
  #NovaLibvirtTxQueueSize: 1024

  #NovaPCIPassthrough:
  #  - devname: "p7p3"
  #    trusted: "true"
  #    physical_network: "sriov-1"
  #  - devname: "p7p4"
  #    trusted: "true"
  #    physical_network: "sriov-2"
  #  - devname: "p5p1"
  #    trusted: "true"
  #    physical_network: "sriov-3"
  #  - devname: "p5p2"
  #    trusted: "true"
  #    physical_network: "sriov-3"

  #NeutronPhysicalDevMappings: "sriov-1:p7p3,sriov-2:p7p4,sriov-3:p5p1,sriov-3:p5p2"
  #NeutronSriovNumVFs: "p7p3:5,p7p4:5,p5p1:5,p5p2:5"

  ##########################
  # OVS DPDK configuration #
  ##########################
  ComputeOvsDpdkSriovParameters:
    OvsEnableDpdk: true
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=32 iommu=pt intel_iommu=on isolcpus=2-19,22-39"
    TunedProfileName: "cpu-partitioning"
    IsolCpusList: "2-19,22-39"
    NovaVcpuPinSet: ['4-19,24-39']
    NovaReservedHostMemory: 4096
    OvsDpdkSocketMemory: "3072,1024"
    OvsDpdkMemoryChannels: "4"
    #OvsDpdkCoreList: "0,20,1,21"
    OvsDpdkCoreList: "0-1,20-21,24"
    OvsPmdCoreList: "2,22,3,23"
    NovaComputeCpuSharedSet: [0,20,1,21]
    # below lines are for history - now this is resolved and we are not
    # required to pass extra hiera data variables - refer BZ -
    # https://bugzilla.redhat.com/show_bug.cgi?id=1617927
    NovaLibvirtRxQueueSize: 1024
    NovaLibvirtTxQueueSize: 1024

  NovaPCIPassthrough:
    - devname: "p7p3"
      trusted: "true"
      physical_network: "sriov-1"
    - devname: "p7p4"
      trusted: "true"
      physical_network: "sriov-2"
    #- devname: "p5p1"
    #  trusted: "true"
    #  physical_network: "sriov-3"
    #- devname: "p5p2"
    #  trusted: "true"
    #  physical_network: "sriov-3"

  NeutronPhysicalDevMappings: "sriov-1:p7p3,sriov-2:p7p4"
  NeutronSriovNumVFs: "p7p3:5,p7p4:5"

  ################################
  #OVS DPDK SRIOV Mellanox Config#
  ################################
  ComputeOvsDpdkSriovMellanoxParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=32 iommu=pt intel_iommu=on isolcpus=2-19,22-39"
    TunedProfileName: "cpu-partitioning"
    IsolCpusList: "2-19,22-39"
    OvsEnableDpdk: true
    NovaVcpuPinSet: ['4-19,24-39']
    NovaReservedHostMemory: 4096
    OvsDpdkSocketMemory: "3072,1024"
    OvsDpdkMemoryChannels: "4"
    #OvsDpdkCoreList: "0,20,1,21"
    OvsDpdkCoreList: "0-1,20-21,24"
    OvsPmdCoreList: "2,22,3,23"
    NovaComputeCpuSharedSet: [0,20,1,21]
      # below lines are for history - now this is resolved and we are not
      # required to pass extra hiera data variables - refer BZ -
      # https://bugzilla.redhat.com/show_bug.cgi?id=1617927
    NovaLibvirtRxQueueSize: 1024
    NovaLibvirtTxQueueSize: 1024

  NovaPCIPassthrough:
    - devname: "p7p3"
      trusted: "true"
      physical_network: "sriov-1"
      #- devname: "p7p4"
      #  trusted: "true"
      #  physical_network: "sriov-2"
    - devname: "p5p1"
      trusted: "true"
      physical_network: "sriov-3" 
    - devname: "p5p2"
      trusted: "true"
      physical_network: "sriov-4"

   # NeutronPhysicalDevMappings: "sriov-1:p7p3,sriov-2:p7p4,sriov-3:p5p1,sriov-3:p5p2"
   # NeutronSriovNumVFs: "p7p3:5,p7p4:5,p5p1:5,p5p2:5"
  NeutronPhysicalDevMappings: "sriov-1:p7p3,sriov-3:p5p1,sriov-4:p5p2"
  NeutronSriovNumVFs: "p7p3:5,p5p1:5,p5p2:5"
