parameter_defaults:
  OvercloudControllerFlavor: "controller"
  OvercloudComputeFlavor: "compute"
  OvercloudComputeSriovFlavor: "computeovsdpdk"

  NtpServer: "clock.redhat.com"
  #TimeZone: Kolkata
  SshServerOptions:
    UseDns: 'no'
